---
name: pamtester run of pam_xdg_runtime_dir
on: [push]
jobs:
  pamtester:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install pamtester gcc make libselinux-dev libpam-dev
      - uses: actions/checkout@v4
      - run: make
      - run: sudo make install INSTALLDIR=/usr/lib/x86_64-linux-gnu/security
      - run: sudo cp pamtester/xdg_runtime_dir /etc/pam.d/xdg_runtime_dir
      - run: sudo adduser testuser
      - run: sudo pamtester -v xdg_runtime_dir testuser open_session
      - run: test -d /run/user/$(id -u testuser)
      - run: test $(stat --format=%U /run/user/$(id -u testuser)) == testuser
